# ===============================
# DATABASE (LOCAL)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/smart_dairy?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Sushant

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ===============================
# JWT
# ===============================
app.jwt.secret=MySuperStrongJWTSecretKeyForSmartDairyApplication2026SecureKey123456
app.jwt.expiration-ms=86400000

# ===============================
# TWILIO (LOCAL)
# ===============================
twilio.account.sid=AC54c46c0a9824e3922ce66be7cc99502a
twilio.auth.token=d4d8b9b524353388b5486c35f37606d1
twilio.phone.number=+16416718118

# ===============================
# CLOUDINARY (LOCAL)
# ===============================
cloudinary.cloud-name=exm5hdnu
cloudinary.api-key=865977855261757
cloudinary.api-secret=KvwLOV_3ZDzRZ_mZViB-0WndB4c

# ===============================
# SERVER
# ===============================
server.port=8080